import { useEffect, useRef, useState } from "react";
import { Camera, CameraOff, CheckCircle2, Copy, QrCode, ScanLine, X } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";

import { InlineNotice, StatusBadge } from "../../../components/common/Feedback";
import type { ToastMessage } from "../../../components/common/Feedback";
import { useAppData } from "../../../context/AppDataContext";
import { formatDateTime } from "../../../utils/format";
import { buildAttendanceQrPayload, parseAttendanceQrPayload } from "../qr";

type QrMode = "scan" | "generate";
type CameraState = "idle" | "starting" | "active" | "unsupported" | "denied";
type BarcodeDetectorLike = { detect: (source: ImageBitmapSource) => Promise<Array<{ rawValue: string }>> };
type BarcodeDetectorConstructor = new (options: { formats: string[] }) => BarcodeDetectorLike;

export function QrModeSheet({
  onClose,
  onNotify,
}: {
  onClose: () => void;
  onNotify?: (toast: Omit<ToastMessage, "id">) => void;
}) {
  const { state, currentUser, submitAttendance } = useAppData();
  const sessions = state.events
    .filter((event) => !["Cancelled", "Completed", "Draft"].includes(event.status))
    .sort((a, b) => +new Date(a.date) - +new Date(b.date));
  const [mode, setMode] = useState<QrMode>(currentUser?.role === "admin" ? "generate" : "scan");
  const [generatedEventId, setGeneratedEventId] = useState(sessions[0]?.id ?? "");
  const [scannedEventId, setScannedEventId] = useState("");
  const [scannedCode, setScannedCode] = useState("");
  const [cameraState, setCameraState] = useState<CameraState>("idle");
  const [notice, setNotice] = useState<{ tone: "info" | "success" | "error" | "warning"; title: string; body: string }>({
    tone: "info",
    title: "Scanner ready",
    body: "Start the camera and center a Tutorial Clinic QR code in the frame.",
  });
  const closeRef = useRef<HTMLButtonElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const scanTimer = useRef<number | null>(null);
  const generatedEvent = sessions.find((event) => event.id === generatedEventId);
  const scannedEvent = state.events.find((event) => event.id === scannedEventId);
  const duplicate = Boolean(scannedEvent && state.attendance.some((record) => record.userId === currentUser?.id && record.eventId === scannedEvent.id && record.status !== "Rejected"));

  function releaseCamera(updateState = true) {
    if (scanTimer.current) window.clearTimeout(scanTimer.current);
    scanTimer.current = null;
    streamRef.current?.getTracks().forEach((track) => track.stop());
    streamRef.current = null;
    if (videoRef.current) videoRef.current.srcObject = null;
    if (updateState) setCameraState("idle");
  }

  useEffect(() => {
    closeRef.current?.focus();
    return () => releaseCamera(false);
  }, []);

  function selectMode(nextMode: QrMode) {
    if (nextMode === mode) return;
    releaseCamera();
    setMode(nextMode);
  }

  function recognize(value: string) {
    const payload = parseAttendanceQrPayload(value);
    const event = payload && state.events.find((item) => item.id === payload.eventId && item.attendanceCode.toUpperCase() === payload.code.toUpperCase());
    if (!payload || !event) {
      setNotice({ tone: "error", title: "Unsupported QR code", body: "Use a QR code generated by Tutorial Clinic." });
      return;
    }
    releaseCamera();
    setScannedEventId(event.id);
    setScannedCode(payload.code);
    setNotice({
      tone: "success",
      title: "QR code recognized",
      body: currentUser?.role === "admin" ? "The session and attendance code are valid." : "Review the session, then confirm your attendance.",
    });
  }

  async function startCamera() {
    const Detector = (window as unknown as { BarcodeDetector?: BarcodeDetectorConstructor }).BarcodeDetector;
    if (!navigator.mediaDevices?.getUserMedia || !Detector) {
      setCameraState("unsupported");
      setNotice({ tone: "warning", title: "Scanner unavailable", body: "This browser does not support camera QR detection. Use manual check-in from Attendance." });
      return;
    }
    setCameraState("starting");
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } });
      streamRef.current = stream;
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
        await videoRef.current.play();
      }
      setCameraState("active");
      const detector = new Detector({ formats: ["qr_code"] });
      const scan = async () => {
        if (!videoRef.current || !streamRef.current) return;
        try {
          const results = await detector.detect(videoRef.current);
          if (results[0]?.rawValue) {
            recognize(results[0].rawValue);
            return;
          }
        } catch {
          // A frame can fail while the camera is focusing; keep scanning.
        }
        scanTimer.current = window.setTimeout(scan, 350);
      };
      scan();
    } catch {
      releaseCamera();
      setCameraState("denied");
      setNotice({ tone: "warning", title: "Camera access blocked", body: "Allow camera access in your browser settings, or use manual check-in from Attendance." });
    }
  }

  function resetScanner() {
    setScannedEventId("");
    setScannedCode("");
    setCameraState("idle");
    setNotice({ tone: "info", title: "Scanner ready", body: "Start the camera and center a Tutorial Clinic QR code in the frame." });
  }

  function confirmAttendance() {
    if (!scannedEvent) return;
    const result = submitAttendance(scannedEvent.id, scannedCode, "QR");
    const next = result.ok
      ? { tone: "success" as const, title: "Attendance submitted", body: result.message ?? "Waiting for administrator approval." }
      : { tone: "error" as const, title: "Check-in not submitted", body: result.message };
    setNotice(next);
    onNotify?.({ tone: next.tone, title: next.title, description: next.body });
  }

  async function copyAttendanceCode() {
    if (!generatedEvent) return;
    try {
      await navigator.clipboard.writeText(generatedEvent.attendanceCode);
      onNotify?.({ tone: "success", title: "Attendance code copied", description: `${generatedEvent.title} is ready to share.` });
    } catch {
      onNotify?.({ tone: "warning", title: "Clipboard unavailable", description: "Select and copy the visible attendance code instead." });
    }
  }

  return (
    <div className="confirm-overlay qr-mode-overlay" onMouseDown={onClose}>
      <section className="qr-mode-dialog" role="dialog" aria-modal="true" aria-labelledby="qr-mode-title" onMouseDown={(event) => event.stopPropagation()}>
        <header className="qr-mode-header">
          <div>
            <div className="section-kicker">Quick attendance tool</div>
            <h2 id="qr-mode-title">QR mode</h2>
            <p>Scan a check-in code or generate one for a session.</p>
          </div>
          <button ref={closeRef} className="icon-button rounded-full bg-[#FAF8F2]" type="button" onClick={onClose} aria-label="Close QR mode"><X size={17} /></button>
        </header>

        <div className="qr-mode-tabs" role="tablist" aria-label="QR mode options">
          <button type="button" role="tab" aria-selected={mode === "scan"} className={mode === "scan" ? "is-active" : ""} onClick={() => selectMode("scan")}><ScanLine size={16} /> Scan QR</button>
          <button type="button" role="tab" aria-selected={mode === "generate"} className={mode === "generate" ? "is-active" : ""} onClick={() => selectMode("generate")}><QrCode size={16} /> Generate QR</button>
        </div>

        {mode === "scan" ? (
          <div className="qr-mode-content" role="tabpanel">
            {scannedEvent ? (
              <div className="qr-scan-result">
                <span className="qr-result-icon"><CheckCircle2 /></span>
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-2"><h3>{scannedEvent.title}</h3><StatusBadge status={duplicate ? "Already checked in" : "QR recognized"} /></div>
                  <p>{formatDateTime(scannedEvent.date)} - {scannedEvent.venue}</p>
                  <code>{scannedEvent.attendanceCode}</code>
                </div>
              </div>
            ) : (
              <div className="camera-panel qr-mode-camera">
                <video ref={videoRef} muted playsInline aria-label="QR scanner camera preview" />
                {cameraState !== "active" && (
                  <div className="camera-placeholder">
                    {cameraState === "unsupported" || cameraState === "denied" ? <CameraOff /> : <Camera />}
                    <strong>{cameraState === "unsupported" ? "QR scanning is not supported" : cameraState === "denied" ? "Camera permission was not granted" : "Scan attendance QR"}</strong>
                    <p>{cameraState === "unsupported" || cameraState === "denied" ? "Manual code entry remains available from the Attendance page in the navigation hub." : "Allow camera access and hold the code inside the frame."}</p>
                    {cameraState === "idle" && <button className="primary-button" type="button" onClick={startCamera}><ScanLine size={15} /> Start scanner</button>}
                    {cameraState === "starting" && <StatusBadge status="Starting camera" />}
                  </div>
                )}
                {cameraState === "active" && <><span className="qr-scan-frame" aria-hidden="true" /><button className="secondary-button camera-stop" type="button" onClick={() => releaseCamera()}>Stop camera</button></>}
              </div>
            )}
            <InlineNotice tone={notice.tone} title={notice.title}>{notice.body}</InlineNotice>
            <div className="qr-mode-actions">
              {scannedEvent && <button className="secondary-button" type="button" onClick={resetScanner}>Scan another</button>}
              {scannedEvent && currentUser?.role !== "admin" && <button className="primary-button" type="button" disabled={duplicate} onClick={confirmAttendance}><CheckCircle2 size={15} /> Confirm attendance</button>}
            </div>
          </div>
        ) : (
          <div className="qr-mode-content" role="tabpanel">
            {generatedEvent ? (
              <>
                <label className="form-field">
                  <span>Session</span>
                  <select value={generatedEventId} onChange={(event) => setGeneratedEventId(event.target.value)}>
                    {sessions.map((event) => <option key={event.id} value={event.id}>{event.title} - {formatDateTime(event.date)}</option>)}
                  </select>
                </label>
                <div className="qr-generator-summary"><div><strong>{generatedEvent.title}</strong><span>{formatDateTime(generatedEvent.date)} - {generatedEvent.venue}</span></div><StatusBadge status={generatedEvent.status} /></div>
                <div className="qr-code-panel qr-mode-code-panel">
                  <QRCodeSVG value={buildAttendanceQrPayload(generatedEvent.id, generatedEvent.attendanceCode)} size={220} level="M" marginSize={2} title={`Attendance QR for ${generatedEvent.title}`} />
                </div>
                <div className="qr-code-value"><span>{generatedEvent.attendanceCode}</span><button type="button" onClick={copyAttendanceCode}><Copy size={14} /> Copy code</button></div>
                <p className="qr-help">The QR contains this session's ID and attendance code. Share it only when check-in is open.</p>
              </>
            ) : (
              <InlineNotice tone="warning" title="No sessions available">Create or publish a session before generating an attendance QR code.</InlineNotice>
            )}
          </div>
        )}
      </section>
    </div>
  );
}
