import { useMemo, useState } from "react";
import { Crown, Search, Trophy } from "lucide-react";
import { EmptyState } from "../../../components/common/Feedback";
import { getUserPoints, useAppData } from "../../../context/AppDataContext";
import type { YearLevel } from "../../../types/common";

export function LeaderboardPage() {
  const { state, currentUser } = useAppData(); const [year, setYear] = useState<"All" | YearLevel>("All"); const [query, setQuery] = useState("");
  const ranked = useMemo(() => state.users.filter((user) => user.role !== "admin" && user.active && (year === "All" || user.yearLevel === year) && (!query || `${user.name} ${user.studentId}`.toLowerCase().includes(query.toLowerCase()))).map((user) => ({ user, points: getUserPoints(state, user.id) })).sort((a, b) => b.points - a.points || a.user.name.localeCompare(b.user.name)).map((item, index) => ({ ...item, rank: index + 1 })), [query, state, year]); const podium = [ranked[1], ranked[0], ranked[2]].filter(Boolean); const me = ranked.find((item) => item.user.id === currentUser?.id);
  return <div className="h-full overflow-y-auto"><div className="mx-auto max-w-6xl px-4 py-6 sm:px-6 lg:px-10 lg:py-8"><header><div className="section-kicker">Contribution standings</div><h1 className="page-heading">Leaderboard</h1><p className="page-description">A consistent ranking calculated from the same point transactions shown on student profiles.</p></header><section className="mt-6 flex flex-col gap-3 rounded-xl bg-white p-4 demo-card sm:flex-row"><label className="search-field flex-1"><Search size={15} /><span className="sr-only">Search leaderboard</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search student" /></label><div className="flex flex-wrap gap-2">{(["All", "Freshman", "Sophomore", "Junior", "Senior"] as const).map((item) => <button key={item} className={`filter-chip ${year === item ? "is-active" : ""}`} onClick={() => setYear(item)}>{item}</button>)}</div></section>{ranked.length ? <><section className="leader-podium">{podium.map((item) => <article className={item.rank === 1 ? "is-first" : ""} key={item.user.id}>{item.rank === 1 && <Crown className="crown" />}<div className="podium-avatar">{item.user.name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</div><span className="podium-rank">{item.rank}</span><h2>{item.user.name}</h2><p>{item.user.yearLevel}</p><strong>{item.points} pts</strong></article>)}</section><section className="mt-8 rounded-xl bg-white p-5 demo-card"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Full ranking</h2><Trophy size={20} color="#F5A623" /></div><ul className="mt-4">{ranked.map((item) => <li className={`leader-row ${item.user.id === currentUser?.id ? "is-me" : ""}`} key={item.user.id}><span>{item.rank}</span><div className="leader-initials">{item.user.name[0]}</div><div className="flex-1"><strong>{item.user.name}{item.user.id === currentUser?.id && " - you"}</strong><small>{item.user.yearLevel} - {item.user.section}</small></div><strong>{item.points} pts</strong></li>)}</ul></section>{me && <div className="sticky-summary">You are ranked <strong>#{me.rank}</strong> in {year === "All" ? "the program" : year} with <strong>{me.points} points</strong>.</div>}</> : <div className="mt-5"><EmptyState title="No students found" body="Try another year level or search." /></div>}</div></div>;
}
