import { useMemo, useState } from "react";
import { Megaphone, Pin, Search } from "lucide-react";
import { EmptyState, StatusBadge } from "../../../components/common/Feedback";
import { useAppData } from "../../../context/AppDataContext";
import { formatDateTime } from "../../../utils/format";

export function AnnouncementsPage() {
  const { state, currentUser, markAnnouncementRead } = useAppData();
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("All");
  const items = useMemo(() => state.announcements.filter((item) => (item.audience === "All" || item.audience === currentUser?.yearLevel) && (!query || `${item.title} ${item.body}`.toLowerCase().includes(query.toLowerCase())) && (filter === "All" || (filter === "Pinned" ? item.pinned : !item.readBy.includes(currentUser?.id ?? "")))).sort((a, b) => Number(b.pinned) - Number(a.pinned) || +new Date(b.publishedAt) - +new Date(a.publishedAt)), [currentUser?.id, currentUser?.yearLevel, filter, query, state.announcements]);
  return <div className="h-full overflow-y-auto"><div className="mx-auto max-w-4xl px-4 py-6 sm:px-6 lg:px-10 lg:py-8"><div className="section-kicker">Community updates</div><h1 className="page-heading">Announcements</h1><p className="page-description">Important schedules, reminders, and Computer Science Society notices.</p><div className="mt-6 flex flex-col gap-3 rounded-xl bg-white p-4 demo-card sm:flex-row"><label className="search-field flex-1"><Search size={15} /><span className="sr-only">Search announcements</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search announcements" /></label><div className="flex gap-2">{["All", "Unread", "Pinned"].map((item) => <button key={item} className={`filter-chip ${filter === item ? "is-active" : ""}`} onClick={() => setFilter(item)}>{item}</button>)}</div></div>{items.length ? <div className="mt-4 grid gap-3">{items.map((item) => { const read = item.readBy.includes(currentUser?.id ?? ""); return <article key={item.id} className={`announcement-card ${read ? "is-read" : ""}`} onClick={() => markAnnouncementRead(item.id)}><div className="flex items-start gap-3"><span className="notification-type-icon"><Megaphone size={17} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2>{item.title}</h2>{item.pinned && <StatusBadge status="Pinned" />}{!read && <StatusBadge status="Unread" />}</div><p>{item.body}</p><div className="mt-3 flex items-center gap-2 text-xs text-[#6F6F6F]">{item.pinned && <Pin size={12} />}Published {formatDateTime(item.publishedAt)} - {item.audience}</div></div></div></article>; })}</div> : <div className="mt-5"><EmptyState icon={<Megaphone size={18} />} title="No announcements found" body="Try another search or filter." /></div>}</div></div>;
}
