import { useMemo, useState } from "react";
import { Check, Download, Eye, Search, X } from "lucide-react";
import { EmptyState, InlineNotice, StatusBadge } from "../../../components/common/Feedback";
import type { ToastMessage } from "../../../components/common/Feedback";
import { useAppData } from "../../../context/AppDataContext";
import type { DemoNote } from "../../../types/app";
import { downloadCsv, formatDateTime } from "../../../utils/format";
import { NotePreviewModal } from "../../notes/components/NotePreviewModal";

export function AdminNotesApprovalPage({ onNotify }: { onNotify?: (toast: Omit<ToastMessage, "id">) => void }) {
  const { state, moderateNote } = useAppData(); const [query, setQuery] = useState(""); const [status, setStatus] = useState("Pending"); const [subjectId, setSubjectId] = useState("All"); const [preview, setPreview] = useState<DemoNote | null>(null); const [reject, setReject] = useState<DemoNote | null>(null);
  const notes = useMemo(() => state.notes.filter((note) => (status === "All" || note.status === status) && (subjectId === "All" || note.subjectId === subjectId) && (!query || `${note.title} ${note.description} ${note.tags.join(" ")} ${state.users.find((item) => item.id === note.uploaderId)?.name}`.toLowerCase().includes(query.toLowerCase()))).sort((a, b) => +new Date(b.updatedAt) - +new Date(a.updatedAt)), [query, state.notes, state.users, status, subjectId]);
  async function approve(note: DemoNote) { const result = await moderateNote(note.id, "Approved"); onNotify?.({ tone: result.ok ? "success" : "error", title: result.ok ? "Note approved" : "Unable to approve", description: result.ok ? "The note is now visible in the library and 60 points were awarded." : result.message }); }
  function exportRows() { downloadCsv("tutorial-clinic-note-moderation.csv", notes.map((note) => ({ title: note.title, subject: state.subjects.find((item) => item.id === note.subjectId)?.code, uploader: state.users.find((item) => item.id === note.uploaderId)?.name, submitted: formatDateTime(note.createdAt), status: note.status, rejection_reason: note.rejectionReason, file: note.fileName }))); onNotify?.({ tone: "success", title: "Moderation CSV exported", description: `${notes.length} visible notes were included.` }); }
  const pending = state.notes.filter((item) => item.status === "Pending").length;
  return <div className="h-full overflow-y-auto"><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-10 lg:py-8"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="section-kicker">Notes moderation</div><h1 className="page-heading">Review student uploads</h1><p className="page-description">Preview submissions, approve useful resources, and give clear rejection feedback.</p></div><button className="secondary-button" onClick={exportRows}><Download size={15} /> Export CSV</button></header><section className="mt-6 grid gap-3 rounded-xl bg-white p-4 demo-card md:grid-cols-[1fr_190px_190px]"><label className="search-field"><Search size={15} /><span className="sr-only">Search submitted notes</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search title or uploader" /></label><label className="compact-field"><span>Status</span><select value={status} onChange={(e) => setStatus(e.target.value)}>{["All", "Pending", "Approved", "Rejected", "Draft"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="compact-field"><span>Subject</span><select value={subjectId} onChange={(e) => setSubjectId(e.target.value)}><option value="All">All subjects</option>{state.subjects.map((item) => <option key={item.id} value={item.id}>{item.code}</option>)}</select></label></section><div className="mt-4"><StatusBadge status={`${pending} pending review`} /></div>{notes.length ? <div className="mt-4 grid gap-3">{notes.map((note) => { const uploader = state.users.find((item) => item.id === note.uploaderId); const subject = state.subjects.find((item) => item.id === note.subjectId); return <article className="moderation-card" key={note.id}><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2>{note.title}</h2><StatusBadge status={note.status} /><StatusBadge status={subject?.code ?? "Subject"} /></div><p>{note.description}</p><div className="mt-2 text-xs text-[#6F6F6F]">{uploader?.name} - {formatDateTime(note.updatedAt)} - {note.fileName ?? "No file"}</div>{note.rejectionReason && <InlineNotice tone="error" title="Previous rejection reason">{note.rejectionReason}</InlineNotice>}</div><div className="flex shrink-0 flex-wrap gap-2"><button className="secondary-button" onClick={() => setPreview(note)}><Eye size={14} /> Preview</button>{note.status === "Pending" && <><button className="primary-button" onClick={() => approve(note)}><Check size={14} /> Approve</button><button className="secondary-button danger-text" onClick={() => setReject(note)}><X size={14} /> Reject</button></>}</div></article>; })}</div> : <div className="mt-5"><EmptyState title="No notes in this view" body="Change the moderation filters or wait for new student submissions." /></div>}</div><NotePreviewModal note={preview} onClose={() => setPreview(null)} />{reject && <RejectModal note={reject} onClose={() => setReject(null)} onNotify={onNotify} />}</div>;
}
function RejectModal({ note, onClose, onNotify }: { note: DemoNote; onClose: () => void; onNotify?: (toast: Omit<ToastMessage, "id">) => void }) { const { moderateNote } = useAppData(); const [reason, setReason] = useState(""); const [error, setError] = useState(""); async function reject() { const result = await moderateNote(note.id, "Rejected", reason); if (!result.ok) { setError(result.message); return; } onNotify?.({ tone: "warning", title: "Note rejected", description: "The student can now see the reason and resubmit." }); onClose(); } return <div className="confirm-overlay" onMouseDown={onClose}><div className="entity-detail-dialog" role="dialog" aria-modal="true" onMouseDown={(e) => e.stopPropagation()}><header><div><div className="section-kicker">Required feedback</div><h2>Reject {note.title}?</h2></div><button className="icon-button rounded-full bg-[#FAF8F2]" onClick={onClose}><X size={16} /></button></header>{error && <InlineNotice tone="error" title="Rejection not saved">{error}</InlineNotice>}<label className="form-field mt-5"><span>Rejection reason</span><textarea rows={5} value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Explain exactly what the student should correct before resubmitting." /></label><footer><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button danger-button" onClick={reject}>Reject note</button></footer></div></div>; }
