import { useState } from "react";
import { Accessibility, BellRing, Check, Eye, RotateCcw, ShieldCheck } from "lucide-react";
import type { ToastMessage } from "../../../components/common/Feedback";
import { InlineNotice } from "../../../components/common/Feedback";
import { useAppData } from "../../../context/AppDataContext";
import { defaultPreferences } from "../../../data/seed";
import type { Preferences } from "../../../types/app";

export function SettingsPage({ onNotify }: { onNotify?: (toast: Omit<ToastMessage, "id">) => void }) {
  const { state, currentUser, updatePreferences } = useAppData(); const persisted = currentUser ? state.preferences[currentUser.id] ?? defaultPreferences : defaultPreferences; const [preferences, setPreferences] = useState<Preferences>(persisted);
  function toggle(key: keyof Preferences) { setPreferences((current) => ({ ...current, [key]: !current[key] })); }
  function save() { updatePreferences(preferences); onNotify?.({ tone: "success", title: "Preferences saved", description: "Your display and notification preferences are stored with this account." }); }
  function reset() { setPreferences({ ...defaultPreferences }); updatePreferences({ ...defaultPreferences }); onNotify?.({ tone: "info", title: "Preferences reset", description: "Default settings were restored." }); }
  if (!currentUser) return null;
  return <div className="h-full overflow-y-auto"><div className="mx-auto max-w-6xl px-4 py-6 sm:px-6 lg:px-10 lg:py-8"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="section-kicker">Account</div><h1 className="page-heading">Settings</h1><p className="page-description">Tune accessibility, display density, and in-app update preferences.</p></div><button className="secondary-button" onClick={reset}><RotateCcw size={15} /> Reset defaults</button></header><div className="mt-6 grid items-start gap-5 xl:grid-cols-[1fr_310px]"><div className="grid gap-5"><SettingsSection icon={<Accessibility />} title="Accessibility and display" description="Choose calmer motion, stronger contrast, or denser desktop navigation."><Preference title="Reduce motion" body="Stops page transitions and hover movement." checked={preferences.reducedMotion} onClick={() => toggle("reducedMotion")} /><Preference title="Higher contrast" body="Strengthens secondary text and control boundaries." checked={preferences.highContrast} onClick={() => toggle("highContrast")} /><Preference title="Compact navigation" body="Fits more destinations in the desktop sidebar." checked={preferences.compactNavigation} onClick={() => toggle("compactNavigation")} /></SettingsSection><SettingsSection icon={<BellRing />} title="Notification preferences" description="These settings prepare the UI for future backend notification delivery."><Preference title="Session reminders" body="RSVP reminders and venue changes." checked={preferences.sessionReminders} onClick={() => toggle("sessionReminders")} /><Preference title="Notes review updates" body="Approval and rejection results." checked={preferences.noteUpdates} onClick={() => toggle("noteUpdates")} /><Preference title="Leaderboard updates" body="Rank changes and milestones." checked={preferences.leaderboardUpdates} onClick={() => toggle("leaderboardUpdates")} /></SettingsSection><div className="flex justify-end"><button className="primary-button" onClick={save}><Check size={15} /> Save preferences</button></div></div><aside className="rounded-xl bg-white p-5 demo-card"><div className="profile-avatar small"><Eye /></div><h2 className="mt-3 text-lg font-bold">{currentUser.name}</h2><p className="text-sm text-[#6F6F6F]">{currentUser.studentId}</p><dl className="detail-list"><div><dt>Account setup</dt><dd>{currentUser.accountSetup.completed ? "Complete" : "Pending"}</dd></div><div><dt>Backup email</dt><dd>{currentUser.accountSetup.backupEmail ?? "Not set"}</dd></div><div><dt>Access</dt><dd>{currentUser.role}</dd></div></dl><InlineNotice tone="warning" title="Local account storage"><ShieldCheck size={14} className="inline" /> Account setup details are not securely authenticated.</InlineNotice></aside></div></div></div>;
}
function SettingsSection({ icon, title, description, children }: { icon: React.ReactNode; title: string; description: string; children: React.ReactNode }) { return <section className="settings-section"><div className="settings-section-heading"><span>{icon}</span><div><h2>{title}</h2><p>{description}</p></div></div><div className="settings-list">{children}</div></section>; }
function Preference({ title, body, checked, onClick }: { title: string; body: string; checked: boolean; onClick: () => void }) { return <div className="preference-row"><div className="flex-1"><div className="preference-title">{title}</div><div className="preference-body">{body}</div></div><button type="button" className="preference-switch" role="switch" aria-checked={checked} aria-label={title} onClick={onClick}><span /></button></div>; }
