import { useMemo, useState } from "react";
import { Search, TrendingDown, TrendingUp, Trophy } from "lucide-react";
import { EmptyState, StatusBadge } from "../../../components/common/Feedback";
import { useAppData } from "../../../context/AppDataContext";
import { formatDateTime } from "../../../utils/format";

export function PointHistoryPage() {
  const { state, currentUser, currentPoints } = useAppData();
  const [query, setQuery] = useState("");
  const [kind, setKind] = useState("All");
  const items = useMemo(() => state.points.filter((item) => item.userId === currentUser?.id && (kind === "All" || item.relatedType === kind) && (!query || item.reason.toLowerCase().includes(query.toLowerCase()))).sort((a, b) => +new Date(b.createdAt) - +new Date(a.createdAt)), [currentUser?.id, kind, query, state.points]);
  const earned = state.points.filter((item) => item.userId === currentUser?.id && item.points > 0).reduce((sum, item) => sum + item.points, 0);
  const deducted = state.points.filter((item) => item.userId === currentUser?.id && item.points < 0).reduce((sum, item) => sum + Math.abs(item.points), 0);
  return <div className="h-full overflow-y-auto"><div className="mx-auto max-w-5xl px-4 py-6 sm:px-6 lg:px-10 lg:py-8"><div className="section-kicker">Participation record</div><h1 className="page-heading">Point History</h1><p className="page-description">A transparent record of points earned, deducted, and adjusted for your Tutorial Clinic account.</p><section className="mt-6 grid gap-3 sm:grid-cols-3"><Summary icon={<Trophy />} label="Current balance" value={currentPoints} /><Summary icon={<TrendingUp />} label="Points earned" value={earned} /><Summary icon={<TrendingDown />} label="Points deducted" value={deducted} /></section><div className="mt-5 flex flex-col gap-3 rounded-xl bg-white p-4 demo-card sm:flex-row"><label className="search-field flex-1"><Search size={15} /><span className="sr-only">Search point history</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search reasons" /></label><label className="compact-field sm:w-48"><span>Type</span><select value={kind} onChange={(event) => setKind(event.target.value)}>{["All", "Attendance", "Note", "Adjustment", "Account"].map((item) => <option key={item}>{item}</option>)}</select></label></div>{items.length ? <ul className="mt-4 grid gap-2">{items.map((item) => <li key={item.id} className="history-row"><div><div className="font-bold">{item.reason}</div><div className="mt-1 text-xs text-[#6F6F6F]">{formatDateTime(item.createdAt)}</div></div><div className="flex items-center gap-3"><StatusBadge status={item.relatedType} /><strong className={item.points >= 0 ? "text-[#9A5D0B]" : "text-[#B94B35]"}>{item.points > 0 ? "+" : ""}{item.points}</strong></div></li>)}</ul> : <div className="mt-5"><EmptyState title="No point transactions found" body="Try changing the search or transaction type." /></div>}</div></div>;
}
function Summary({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="rounded-xl bg-white p-4 demo-card"><div className="flex items-center justify-between text-[#F5A623]"><span className="[&>svg]:h-[18px] [&>svg]:w-[18px]">{icon}</span><strong className="text-2xl text-[#1C1C1C]">{value}</strong></div><div className="mt-3 text-xs font-bold text-[#6F6F6F]">{label}</div></div>; }
